# Generated by Django 2.0 on 2018-05-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ex', '0003_auto_20180521_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_avatar',
            name='avatar',
            field=models.ImageField(upload_to='media/static/media/avatar'),
        ),
    ]
