# Generated by Django 2.0 on 2018-05-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ex', '0004_auto_20180521_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_avatar',
            name='avatar',
            field=models.ImageField(upload_to='static/media/avatar'),
        ),
    ]
